### ISSUE TITLE
建议：框架异常alias关联自定义异常注解支持数组

### ISSUE THREAD

**Issue by huguangquan** [feiniaojin/graceful-response#13]
public @interface ExceptionAliasFor {
    String code() default "ERROR";
    String msg() default "Poor network quality!";
    Class<? extends Throwable> aliasFor();
}
Class<? extends Throwable> aliasFor();  建议考虑支持数组， 这样springmvc的框架的多种类似异常可以只定义一个异常进行关联。

**Comment by feiniaojin** [comment]
您好，感谢提出宝贵的意见。

您反馈的建议，已在3.0版本解决。
