### ISSUE TITLE
通过配置来支持例外请求

### ISSUE THREAD

**Issue by budongzhd** [feiniaojin/graceful-response#15]
例如在swagger中，对请求的处理已经固定下来，加上graceful-reponse后，返回数据的格式变化导致原来的前端逻辑走不下去了。

**Comment by TOP-LH** [comment]
> 例如在swagger中，对请求的处理已经固定下来，加上graceful-reponse后，返回数据的格式变化导致原来的前端逻辑走不下去了。

我正在优化这个, 马上提交PR

**Comment by feiniaojin** [comment]
> > 例如在swagger中，对请求的处理已经固定下来，加上graceful-reponse后，返回数据的格式变化导致原来的前端逻辑走不下去了。
> 
> 我正在优化这个, 马上提交PR

swagger这块的适配逻辑，规划是不在graceful-response里面硬编码做适配，而是单拉一个项目（https://github.com/feiniaojin/graceful-response-swagger ）做这件事情。工程之前建好了，但是最近比较忙没来得及搞，有兴趣我把你拉进去啊

**Comment by TOP-LH** [comment]
> > > 例如在swagger中，对请求的处理已经固定下来，加上graceful-reponse后，返回数据的格式变化导致原来的前端逻辑走不下去了。
> > 
> > 
> > 我正在优化这个, 马上提交PR
> 
> swagger这块的适配逻辑，规划是不在graceful-response里面硬编码做适配，而是单拉一个项目（https://github.com/feiniaojin/graceful-response-swagger ）做这件事情。工程之前建好了，但是最近比较忙没来得及搞，有兴趣我把你拉进去啊

https://github.com/feiniaojin/graceful-response 我想参加的是这个项目

**Comment by budongzhd** [comment]
> > > 例如在swagger中，对请求的处理已经固定下来，加上graceful-reponse后，返回数据的格式变化导致原来的前端逻辑走不下去了。
> > 
> > 
> > 我正在优化这个, 马上提交PR
> 
> swagger这块的适配逻辑，规划是不在graceful-response里面硬编码做适配，而是单拉一个项目（https://github.com/feiniaojin/graceful-response-swagger ）做这件事情。工程之前建好了，但是最近比较忙没来得及搞，有兴趣我把你拉进去啊

我提出的例外是在graceful-response上做一个通用的可配置的例外，不是指硬编码来适配swagger，只不过是拿swagger举个例子。建议最好把graceful-response做成一定范围内通用的，而不是针对每个场景都开一个新项目。

**Comment by feiniaojin** [comment]
3.2.0版本后可以支持。

spring boot 2.7版本使用 3.2.0-boot2；spring boot 3.0以上版本使用 3.2.0-boot3
