### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by xuzhou2016** [feiniaojin/graceful-response#21]
你好：
      我用 graceful-response  作为返回的统一格式， 这个很棒！
      但是遇到一个问题： 就是当你不确定异常的时候， 返回的 msg, 并不能把错误显示出来。 
      ----------希望： 有异常的时候， 后端的异常信息， 放到 返回的 msg 里面   msg = e.getMessage()

     比如：  有一 方法
 @GetMapping("/me")
  public void testNoResponse() {

    //    String name = "zhou";
    //    Assert.isTrue(name == "wang", "姓名不相等");
    int sum = 9 / 0;
    System.out.println("me:" + LocalDateTime.now());
  }

我希望  msg= 'divide by zero'  (后端异常的message, 直接放到 msg 中）
谢谢！

**Comment by feiniaojin** [comment]
您好，感谢认可。

不太建议直接把异常的message返回给前端用户，因为异常的的message一般不具备可读性，主要是面向开发者自己排查问题的，不应该让用户接触到这么具体的异常信息。

**Comment by xuzhou2016** [comment]
你可以给个开关（配置）， 默认关闭，
但开发人员，可以自己打开，  上线的时候， 关闭。
但目前  没有这样的配置

**Comment by xuzhou2016** [comment]
生产上的问题， 有时候，无法获取日志log,  但如果 异常  直接显示在 页面， 5秒后，消失，  这个客户是可以接受的。（服务器异常，请联系管理员----  这个太笼统，无法定位错误）
