### ISSUE TITLE
GlobalExceptionAdvice类空指针异常

### ISSUE THREAD

**Issue by systemoutprintlnnnn** [feiniaojin/graceful-response#25]
GlobalExceptionAdvice类中的属性不知道为什么带@Resource注解的属性都没有注入
包括ResponseFactory、GracefulResponseProperties、ResponseStatusFactory

java.lang.NullPointerException: Cannot invoke "com.feiniaojin.gracefulresponse.GracefulResponseProperties.isPrintExceptionInGlobalAdvice()" because "this.gracefulResponseProperties" is null
	at com.feiniaojin.gracefulresponse.advice.GlobalExceptionAdvice.exceptionHandler(GlobalExceptionAdvice.java:57) ~[graceful-response-3.1.0.jar:na]

**Comment by systemoutprintlnnnn** [comment]
我的springboot版本是3.x，是否和这个相关

**Comment by feiniaojin** [comment]
您好，我们分别对Spring Boot 2.x和3.x进行了适配，欢迎选择对应的版本。

| Spring Boot版本 | Graceful Response版本 | graceful-response-example分支        |
|---------------|---------------------|-------------|
| 2.x           | 3.2.0-boot2         | 3.2.0-boot2 |
| 3.x           | 3.2.0-boot3         | 3.2.0-boot3 |
