### ISSUE TITLE
希望可以支持断言信息统一返回

### ISSUE THREAD

**Issue by Shuimuxiaochao** [feiniaojin/graceful-response#30]
public boolean deleteSimple(Serializable id)
    {
        Assert.isTrue(id.equals(65), "ID错误了");
        return this.remove(id);
    }

例如上面代码，有时候确实需要在业务逻辑中通过断言判断，提示用户简洁的异常信息，这些信息通常是可以让用户自己处理的，由于自己参数不当，或者传递信息有误导致，通过控制的校验函数可能不会那么全面的校验，具体业务的限制我认为是必要的。
所以是否可以支持断言信息的统一封装提供呢？

**Comment by Aurorxa** [comment]
我已经提交了 PR，就看是否能合并了

**Comment by Shuimuxiaochao** [comment]
> 我已经提交了 PR，就看是否能合并了

兄弟 你的pr有对断言处理进行增强吗

**Comment by feiniaojin** [comment]
非常好的想法，我们会进行调研，欢迎假如我们的用户群，持续关注进站
