### ISSUE TITLE
关于404被包装的疑问

### ISSUE THREAD

**Issue by some0ne1980** [feiniaojin/graceful-response#31]
您好。非常感谢您的分享。测试时有一个疑问如下。
当访问路径错误时，正常应该返回http状态404的报错。但是这个报错也被包装成下面这样了：
{
    "code": "0",
    "msg": "ok",
    "data": {
        "timestamp": "2023-12-08T01:44:06.482+00:00",
        "status": 404,
        "error": "Not Found",
        "message": "",
        "path": "/responseDemo/testExcepti"
    }
}
如果按说明文档中“接口开发规范”页的内容，这种层面的报错不应该去包装吧？

**Comment by some0ne1980** [comment]
呃。我错了。按照文档反而正是要包装。就是前端看起来会有点怪。

**Comment by feiniaojin** [comment]
参考 https://github.com/feiniaojin/graceful-response-example 的`异常别名`和`application.yaml`配置，您将得到下面的response。

<img width="468" alt="image" src="https://github.com/feiniaojin/graceful-response/assets/38030904/68cf26aa-5b8c-4851-8c69-ff8a33e71152">

```json
{"code":"1404","msg":"not found","data":{}}
```
