### ISSUE TITLE
建议支持多种响应风格并存

### ISSUE THREAD

**Issue by zkyne** [feiniaojin/graceful-response#32]
有些场景上面对接多个业务方,而各个业务方处理响应风格不一
如果使用这个工具无法做到
建议加个注解指定响应的class,如果有注解,该方法或该类的响应风格走指定的
如果没有直接走全局

**Comment by feiniaojin** [comment]
非常感谢您地建议，关于您提到的这个场景，我们暂时不会考虑进行支持。理由如下：

- 假如一个应用中有80%的接口采用同样的响应风格进行返回，那我们目前已经支持了80%的接口，剩下的20%属于是极少数，，完全可以在接口中手工控制，工作量不会太大；

- 假如一个应用中，存在非常多的响应风格，每一种风格出现的频率差不了太多，此时应用层面都没有办法统一风格，我们更不能了，实际上加个注解和在方法里面手工new Response的工作量是差不多的；

- 不同的风格之间，还有可能存在自定义响应体Reponse类的情况，此时就更复杂了。

我们希望graceful-response能为开发者带来便利，解决高频的需求，满足大部分应用场景，而对于低频的需求，即使技术上没难度，我们也要考虑学习成本。
