### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by dch1314** [feiniaojin/graceful-response#35]
整体用下来感觉挺好，唯一不方便的就是GlobalExceptionAdvice处理了系统的所有异常信息，导致系统中的RuntimeException异常信息无法灵活设置相关信息，建议自定义异常继承GracefulResponseException, GlobalExceptionAdvice只拦截GracefulResponseException异常，其他异常交给用户自行处理。

**Comment by feiniaojin** [comment]
非常感谢，您提的意见很中肯，目前确实捕获了所有的异常，未来版本中我们也会考虑是否进行相应的调整。
