### ISSUE TITLE
能否适配smart-doc 文档生成工具？

### ISSUE THREAD

**Issue by 129duckflew** [feiniaojin/graceful-response#36]
smart-doc是一个轻量级的接口文档生成工具，不同于swagger，这个工具不需要编写侵入式代码来生成文档，而是通过JavaDoc+泛型类型推导实现的。以定义一个用户查询接口举例如下
```java
    /**
     * 根据id获取用户
     * @param userId
     * @return
     * @page
     */
    @GetMapping("/{userId}")
    public CommonResult<User> getUserById(@PathVariable @NotNull(message = "id must be not null") Integer  userId)
    {
        User user = userService.userDetailsById(userId);
        return CommonResult.success(user);
    }
```
按照这个格式，smart-doc会生成一个get请求的文档如下
![image](https://github.com/feiniaojin/graceful-response/assets/62204325/a6a503aa-a149-47b0-9561-bd8a7c3f0ba2)

然而 graceful-responese 也封装了Http接口的返回体 ，也就意味着不需要手动传入泛型，而是框架来封装了,这种情况下是否意味着我无法同时使用2个框架？

**Comment by feiniaojin** [comment]
您好，非常感谢您的关注。

您可以尝试一下在smart-doc中配置responsebodyadvice，将className配置为通用的响应类。

https://smart-doc-group.github.io/#/zh-cn/advanced/config?id=responsebodyadvice

<img width="1057" alt="image" src="https://github.com/feiniaojin/graceful-response/assets/38030904/253b485e-c4c7-48bf-ad0f-c68db0ebd60b">

**Comment by 129duckflew** [comment]
> 您好，非常感谢您的关注。
> 
> 您可以尝试一下在smart-doc中配置responsebodyadvice，将className配置为通用的响应类。
> 
> https://smart-doc-group.github.io/#/zh-cn/advanced/config?id=responsebodyadvice
> 
> <img alt="image" width="1057" src="https://private-user-images.githubusercontent.com/38030904/291971204-253b485e-c4c7-48bf-ad0f-c68db0ebd60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjI2MzcsIm5iZiI6MTcwMzEyMjMzNywicGF0aCI6Ii8zODAzMDkwNC8yOTE5NzEyMDQtMjUzYjQ4NWUtYzRjNy00OGJmLWFkMGYtYzY4ZGIwZWJkNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAxMzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNGQ4YmU1MDE4ZDhhYTBkMjFlNzQxMWE4ZjVkMTE1NjlmN2ZjM2Y5NWY2NGYyYjllMThkMzQwZTc1Njk5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yp9EqoYcOSExTxS7CrwNBQItR5LSxe82FnMd6IiubCA">

将className配置为通用的响应类   是指设置graceful-response中的封装类吗，具体是哪个类呢？

**Comment by feiniaojin** [comment]
Graceful Reponse内部默认有两个响应类，您可以尝试配置一下：

`com.feiniaojin.gracefulresponse.defaults.DefaultResponseImplStyle0`

`com.feiniaojin.gracefulresponse.defaults.DefaultResponseImplStyle1`

如果smart-doc找不到的话，您可以拷贝这两个类的代码到您工程下面，然后再指定即可。
