### ISSUE TITLE
对GracefulResponseException的方法扩展

### ISSUE THREAD

**Issue by spf03** [feiniaojin/graceful-response#44]
您好，有时需要在返回异常信息时，携带一些数据，如何实现？在GracefulResponseException的方法中没有找到能填充data的方法。

**Comment by feiniaojin** [comment]
我们目前有同学在进行这方面的功能开发，预计下个版本能支持

**Comment by feiniaojin** [comment]
4.0.0以上版本已支持该功能，欢迎体验并提供反馈
