### ISSUE TITLE
支持通过配置排除url路径方式放行请求

### ISSUE THREAD

**Issue by weaselveehuang** [feiniaojin/graceful-response#45]
框架支持exclude-packages放行包中的请求，但这还远远不够。如果应用中集成了第三方中间或插件，其中有请求，很多情况下是要放行的，调试时我们很容易通过浏览器控制台获取到url路径，获取具体请求url对应的RequestMapping所在的包是困难的，且是没有必要的。
所以期望可以像权限框架（比如spring security,sa-token）一样，直接配置exclude-path/exclude-url放行请求。

**Comment by feiniaojin** [comment]
很好的提议，未来版本我看可以加入进来

**Comment by feiniaojin** [comment]
@zhouding030 来跟进一下这个需求啊

**Comment by wanggangtie** [comment]
exclude-path=/public/**,/open/**  使用nacos进行动态配置

在Spring Security配置类中添加exclude-path的处理逻辑
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Value("${exclude-path}")
    private String excludePath;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests()
                .antMatchers(excludePath.split(","))
                .permitAll()
                .anyRequest()
                .authenticated()
            .and()
            .formLogin()
            .and()
            .httpBasic();
    }
}

使用@Value注解来读取exclude-path的配置值，并将其用于Spring Security的antMatchers()方法来配置放行的URL。

**Comment by feiniaojin** [comment]
4.0.0以上版本已支持该功能，欢迎体验并提供反馈
