### ISSUE TITLE
ValidationExceptionAdvice类中的exceptionHandler方法判断逻辑疑问

### ISSUE THREAD

**Issue by LordHumphrey** [feiniaojin/graceful-response#46]
**Describe the bug**
最近正在阅读您的项目源码，注意到`ValidationExceptionAdvice`类中的`exceptionHandler`方法存在如下逻辑

```java
if (e instanceof MethodArgumentNotValidException
                || e instanceof BindException) {
            ResponseStatus responseStatus = this.handleBindException((BindException) e);
            return responseFactory.newInstance(responseStatus);
        }
```
这里的`MethodArgumentNotValidException`已经继承了`BindException`类，所以此处似乎只要保留`BindException`即可，但是您一定有自己的想法，所以冒昧问问您这里是如何考虑的？
谢谢。

**Comment by feiniaojin** [comment]
这里应该是从历史代码重构过来的，当时MethodArgumentNotValidException还没有继承BindException，早期会分别对这两个异常进行处理，spring从5.3.0开始，MethodArgumentNotValidException继承BindException，Graceful Reponse也对处理逻辑进行了合并，合并的时候直接把MethodArgumentNotValidException写进去了，直接保留BindException就可以了。

**Comment by feiniaojin** [comment]
可以的啊，特别欢迎踊跃参与，对项目进行完善，更好地支持用户。记得加一下README中的用户群啊
