### ISSUE TITLE
能否增加一个全局默认的参数校验异常信息功能

### ISSUE THREAD

**Issue by Cele4TeR** [feiniaojin/graceful-response#60]
在每个参数校验注解中写message有点繁琐,我想全局同一返回message,我尝试为ValidationException和MethodArgumentNotValidException设置异常别名,但好像不起作用,返回的message要么是不在预期的注解默认message,要么是"msg": "{jakarta.validation.constraints.Pattern.message}"类似的

**Comment by feiniaojin** [comment]
将在5.0.0版本提供
