### ISSUE TITLE
图片验证码接口无法正常使用

### ISSUE THREAD

**Issue by zdt1013** [feiniaojin/graceful-response#7]
使用了本组件后，如果接口使用response方式自定义返回相应内容时，存在兼容问题，比如生成图片验证码的文件流响应给客户端
请问是否考虑兼容？

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!

**Comment by feiniaojin** [comment]
把Controller上面的@RestController改成@Controller，然后图片的方法上也不要加@ResponseBody。

应该是用流回写图片，写完图片之后，方法或者类上面有这两个注解，然后就多返回了报文。
