### ISSUE TITLE
自定义异常是否考虑支持一个异常类型，code, msg可以自定义？

### ISSUE THREAD

**Issue by zdt1013** [feiniaojin/graceful-response#8]
场景是这样的：接口表单提交,校验有大量的参数异常反馈情况，每个类型增加一个异常类会生成很多类，如果一个异常类，可以自定义msg的异常（参数异常类），这样接口返回响应内容可以反馈给前端页面提示。节省冗余类的产生

**Comment by feiniaojin** [comment]
您好，可以升级到2.1版本，使用`GracefulResponse.raiseException(String code, String msg) `方法，详细见README中的3.5
