### ISSUE TITLE
减少异常类的定义

### ISSUE THREAD

**Issue by Joy-Walker** [feiniaojin/graceful-response#9]
异常code和msg与异常类绑定，业务的不同异常情况下有不同的code和msg，进而异常类定义的太多了。

是否考虑在异常类里面包含code和msg属性，这样业务可以抛出同一个异常 如 BizServiceException，而含有不同的code和msg ?

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!

**Comment by feiniaojin** [comment]
您好，可以升级到2.1版本，使用`GracefulResponse.raiseException(String code, String msg) `方法，详细见README中的3.5
